/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcImage {
        /**
          * Render component as 'img' or 'picture'. Default is 'img'.
         */
        "as": 'img' | 'picture';
        /**
          * Text for image's alt attribute.
         */
        "dataAlt": string;
        /**
          * CSS classes to be added on the root (picture) element.
         */
        "dataClass": string;
        /**
          * Image height.
         */
        "dataHeight": string | number;
        "dataSizes": string;
        /**
          * Image src.
         */
        "dataSrc": string;
        "dataSrcset": string;
        "dataWidth": string | number;
    }
}
declare global {
    interface HTMLUcImageElement extends Components.UcImage, HTMLStencilElement {
    }
    var HTMLUcImageElement: {
        prototype: HTMLUcImageElement;
        new (): HTMLUcImageElement;
    };
    interface HTMLElementTagNameMap {
        "uc-image": HTMLUcImageElement;
    }
}
declare namespace LocalJSX {
    interface UcImage {
        /**
          * Render component as 'img' or 'picture'. Default is 'img'.
         */
        "as"?: 'img' | 'picture';
        /**
          * Text for image's alt attribute.
         */
        "dataAlt"?: string;
        /**
          * CSS classes to be added on the root (picture) element.
         */
        "dataClass"?: string;
        /**
          * Image height.
         */
        "dataHeight"?: string | number;
        "dataSizes"?: string;
        /**
          * Image src.
         */
        "dataSrc": string;
        "dataSrcset"?: string;
        "dataWidth"?: string | number;
    }
    interface IntrinsicElements {
        "uc-image": UcImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-image": LocalJSX.UcImage & JSXBase.HTMLAttributes<HTMLUcImageElement>;
        }
    }
}
