/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcImage {
        /**
          * Image alt text.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt
         */
        "dataAlt": string;
        /**
          * CSS class(es) to be added on the <img> tag inside the <picture> element.
         */
        "dataClass": string;
        /**
          * Image height.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-height
         */
        "dataHeight": string | number;
        /**
          * sizes for img tag.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes
         */
        "dataSizes": string;
        /**
          * Image URL. The value of this prop will be set on img tag's src attribute.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-src
         */
        "dataSrc": string;
        /**
          * srcset for img tag.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset
         */
        "dataSrcset": string;
        /**
          * Image width.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width
         */
        "dataWidth": string | number;
    }
}
declare global {
    interface HTMLUcImageElement extends Components.UcImage, HTMLStencilElement {
    }
    var HTMLUcImageElement: {
        prototype: HTMLUcImageElement;
        new (): HTMLUcImageElement;
    };
    interface HTMLElementTagNameMap {
        "uc-image": HTMLUcImageElement;
    }
}
declare namespace LocalJSX {
    interface UcImage {
        /**
          * Image alt text.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt
         */
        "dataAlt"?: string;
        /**
          * CSS class(es) to be added on the <img> tag inside the <picture> element.
         */
        "dataClass"?: string;
        /**
          * Image height.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-height
         */
        "dataHeight"?: string | number;
        /**
          * sizes for img tag.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes
         */
        "dataSizes"?: string;
        /**
          * Image URL. The value of this prop will be set on img tag's src attribute.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-src
         */
        "dataSrc": string;
        /**
          * srcset for img tag.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset
         */
        "dataSrcset"?: string;
        /**
          * Image width.
          * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width
         */
        "dataWidth"?: string | number;
    }
    interface IntrinsicElements {
        "uc-image": UcImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-image": LocalJSX.UcImage & JSXBase.HTMLAttributes<HTMLUcImageElement>;
        }
    }
}
